
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/Provider";
import Breadcrumb from '@/components/molecules/Breadcrumb'; 
import ReportHeader from "@/components/molecules/ReportHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
                <ReportHeader />

          <div className="p- md:p- bg-white border-b shadow-sm m-5">
            <Breadcrumb /> 
          </div>
          
          <main className="p-4 md:p-6">
            {children}
          </main>
          
        </ReduxProvider>
      </body>
    </html>
  );
}